[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "model_backend"
license = {text = "MIT License"}
readme = "README.md"
description = "Model backend for OneHealth project"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
authors = [
  { name="Scientific Software Center", email="ssc@uni-heidelberg.de" },
]
version = "0.0.1"

dependencies = [
  "xarray[parallel]>=2025.4.0",
  "rioxarray>=0.19.0",
  "netcdf4>=1.7.2",
  "geopandas[all]>=1.1.0", 
  "matplotlib>=3.10.3", 
  "numpy>=2.2.6", 
  "dask >=2025.5.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
    "pytest-cov",
]

[project.urls]
Homepage = "https://github.com/ssciwr/onehealth-model-backend"
Issues = "https://github.com/ssciwr/onehealth-model-backend/issues"
